---
title: "calluna_xylem_exploration"
format: html
editor: visual
---

# Calluna xylem exploration

### Loading libraries

```{r}
#| label: libraries
#| message: false
#| warning: false

library(tidyverse)
library(readr)
library(readxl)
library(ggplot2)
library(janitor)
library(plotrix)
library(patchwork)
library(ggdist)
library(lme4)
```

### Import

```{r}
#| label: import
#| message: false
#| warning: false
#| echo: false

#the main dataset is imported in this chunk. many csv files from one directory are imported and combined into one large dataset. the dataset consists of imagej outputs of particle analyses, set with certain parameters.

#set directory. change if you use another path
xylem_area_dir <- "/home/eirik/Documents/skole/r/calluna-hydraulics/raw_data/xylem_area/"

#list each file in the xylem area directory and prepare it for import
xylem_area_files <- list.files(xylem_area_dir, pattern = "\\.csv$", full.names = TRUE)

#create a raw dataset by reading the csv files in the directory and identify them by the filename
xylem_area_raw <- xylem_area_files |>
  setNames(basename(xylem_area_files)) |>
  purrr::map_df(~ readr::read_csv(.x, show_col_types = FALSE), .id = "source_file") |>
  rename_at("...1", ~"xylem_id")
```

```{r}
#| label: damage_import
#| message: false

#this imports the dataset that contains information about the extent of damage from microtome sectioning and growth abnormalities in the calluna that has been sampled for hydraulic analysis. damage for the whole stem, as well as damage in the "cardinal directions" and subsets.

#import damage data
xylem_damage <- read_csv("raw_data/Xylem_damage_report.csv") |>
  mutate(plant = substr(image_id,1,7))
```

### Combining datasets and export of raw data

```{r}
#| label: combination_prep
#creating some new column in the xylem area dataset to allow the use of match arguments so that each dataset can be combined

xylem_area_combined <- xylem_area_raw |>
  #create plant name
  mutate(plant = substr(source_file,1,7)) |>
  #create age class
  mutate(age_class = substr(source_file,1,3)) |>
  #create nin type
  mutate(nin_type = substr(source_file,5,6)) |>
  #create treatment combo
  mutate(treatment = substr(source_file, 1, 6)) |>
  #create plant cardinal direction
  mutate(plant_direction = substr(source_file,1,9)) |>
  #create plant subset
  mutate(plant_subset = substr(source_file,1,11)) |>
  #create own column with the subset number (to match with the damage dataset)
  mutate(subset = substr(source_file,18,18)) |>
  mutate(subset_damage = 1) #1 is just a placeholder, will get replaced in the next chunk

```

```{r}
#| label: combine_damage_dataset

#adding xylem damage to the combined dataset

#add in whole plant damage
xylem_area_combined$whole_plant_damage <- xylem_damage$damage_whole[match(xylem_area_combined$plant, xylem_damage$plant)]

#add in cardinal direction damage
xylem_area_combined$cardinal_direction_damage <- xylem_damage$damage_pic[match(xylem_area_combined$plant_direction, xylem_damage$image_id)]

#add in subset damage
xylem_area_combined$subset1 <- xylem_damage$damage_sub1[match(xylem_area_combined$plant_direction, xylem_damage$image_id)]

xylem_area_combined$subset2 <- xylem_damage$damage_sub2[match(xylem_area_combined$plant_direction, xylem_damage$image_id)]

xylem_area_combined$subset3 <- xylem_damage$damage_sub3[match(xylem_area_combined$plant_direction, xylem_damage$image_id)]

#usig the 3 new columns from above, add the respective damage from the correct subset into this column. 
xylem_area_combined <- xylem_area_combined |>
  mutate(subset_damage = case_when(
    subset == 1 ~ subset1,
    subset == 2 ~ subset2,
    subset == 3 ~ subset3
  ))


#add in warps (mostly growth abnormalities or possibly stretching from sectioning)
xylem_area_combined$warped <- xylem_damage$warped[match(xylem_area_combined$plant_direction, xylem_damage$image_id)]

#add in folds (when the section has folded over it self somewhat)
xylem_area_combined$folds <- xylem_damage$folds[match(xylem_area_combined$plant_direction, xylem_damage$image_id)]

#add in late season missing (where the outermost part of the ring has been teared off)
xylem_area_combined$late_season_missing <- xylem_damage$late_season_missing[match(xylem_area_combined$plant_direction, xylem_damage$image_id)]

#remove the 3 columns with subset damage as they are now redundant
xylem_area_combined <- xylem_area_combined |>
  select(-c(20,21,22))
```

```{r}
#| label: raw_data_export

#in this chunk a csv file containing the raw data will be generated, and uploaded for others to see and use. No filtering or cleaning has taken place so far, only joing the different datasets together to create the calluna hydraulics dataset.

write.csv(xylem_area_combined, "raw_data/DURIN_raw_LygraFire_field_trait_2025.csv")
```

# Plotting

```{r}
#| label: means and plot prepping

#adding means on different levels and adding statistics to visualize the data better

xylem_area_combined <- xylem_area_combined |>
  #creating means at the plant level
  group_by(plant) |>
  mutate(means_plant = mean(Area)) |>
  #creating means at the subset level
  group_by(source_file) |>
  mutate(means_subset = mean(Area)) |>
  group_by(treatment) |>
  mutate(means_treatment = mean(Area)) |>
  mutate(circ = (4*3.14)*(Area/(Perim.*Perim.))) |>
  ungroup()

xylem_area_combined$age_class <- factor(xylem_area_combined$age_class, levels = c("PIO", "BUI", "MAT"))

xylem_area_combined_circ <- xylem_area_combined |>
  filter(circ >= 0.7)

```

### Plant level xylem size vs subset damage

```{r}
#| label: xylem_size_damage_subset
#| message: false
#| warning: false

#simple visiualisation of plant level mean xylem size colored by extent of damage

ggplot(data = xylem_area_combined, mapping = aes(x = plant, y = Area, colour = as.character(as.numeric(subset_damage)))) + geom_point() + facet_wrap(vars(age_class), scales = "free_x") + scale_color_viridis_d()
```

### Plant level xylem mean size vs NiN

```{r}
#| label: xylem_mean_size_nin
#| message: false
#| warning: false

#simple visiualisation of plant level mean xylem size colored by nin type

ggplot(data = xylem_area_combined, mapping = aes(x = plant, y = means_plant, colour = nin_type)) + geom_jitter() + facet_wrap(vars(age_class), scales = "free") + scale_color_viridis_d()
```

### Xylem distribution changes unfiltered vs circularity \> 0.7

```{r}
#| label: xylem_mean_size_nin_subset
#| message: false
#| warning: false

#simple visiualisation of subset level mean xylem size colored by nin type

subset_nin_plot <- ggplot(data = xylem_area_combined, mapping = aes(x = treatment, y = Area, colour = nin_type)) + geom_jitter() + geom_violin() + facet_wrap(vars(age_class), scales = "free") + scale_color_viridis_d() + labs(title = "Unfiltered") + xlab(label = "NiN x Age class") + ylab("Xylem area in µm") + theme(legend.position = "none")

subset_nin_plot_filtered <- ggplot(data = xylem_area_combined_circ, mapping = aes(x = treatment, y = Area, colour = nin_type)) + geom_jitter() + geom_violin() + facet_wrap(vars(age_class), scales = "free") + scale_color_viridis_d() + labs(title = "Circularity > 0.7") + xlab(label = "NiN x Age class") + ylab("Xylem area in µm")

subset_nin_plot + subset_nin_plot_filtered
```

### Distribution of damage index 4 and 5, and the effect of circularity \> 0.7

```{r}
#creating new filtered datasets
xylem_area_damage_5 <- xylem_area_combined |>
  filter(subset_damage == 5)

xylem_area_damage_4 <- xylem_area_combined |>
  filter(subset_damage == 4)

xylem_area_damage_5_filtered <- xylem_area_combined_circ |>
  filter(subset_damage == 5)

xylem_area_damage_4_filtered <- xylem_area_combined_circ |>
  filter(subset_damage == 4)

#create a custom palette to use
palette_damage <- c("orange", "red")


plot_damage_5 <- ggplot() + 
  geom_jitter(data = xylem_area_combined,aes(x = treatment, y = Area), color = "grey") + geom_jitter(data = xylem_area_damage_4, aes(x = treatment, y = Area, color = as.character(as.numeric(subset_damage)))) + geom_jitter(data = xylem_area_damage_5, aes(x = treatment, y = Area, color = as.character(as.numeric(subset_damage)))) + geom_point(data = xylem_area_combined, aes(x = treatment, y = means_treatment), color = "blue") + labs(title = "Unfiltered") + ylab(label = "Xylem vessel area in µm") + xlab(label = "NiN x Age class") + theme(legend.position = "none") + scale_color_manual(values = palette_damage)

plot_damage_5_filtered <- ggplot() + 
  geom_jitter(data = xylem_area_combined_circ,aes(x = treatment, y = Area), color = "grey") + geom_jitter(data = xylem_area_damage_4_filtered, aes(x = treatment, y = Area, color = as.character(as.numeric(subset_damage)))) + geom_jitter(data = xylem_area_damage_5_filtered, aes(x = treatment, y = Area, color = as.character(as.numeric(subset_damage)))) + geom_point(data = xylem_area_combined_circ, aes(x = treatment, y = means_treatment), color = "blue") + labs(title = "Circularity > 0.7") + ylab(label = "Xylem vessel area in µm") + xlab(label = "NiN x Age class") + scale_color_manual(values = palette_damage) + guides(color = guide_legend(title = "Subset damage index"))

plot_damage_5 + plot_damage_5_filtered
```

## Residual plots

```{r}
X <- xylem_area_combined$plant_subset
Y <- xylem_area_combined$means_subset

model <- lm(Y~X)

res <- resid(model)
res
plot(fitted(model), res)
abline(0,0)
```

```{r}
qqnorm(res)
```

```{r}
X1 <- xylem_area_combined$nin_type
X2 <- xylem_area_combined$age_class

model_3x3 <- lm(log(Area) ~ nin_type * age_class, data = xylem_area_combined)

plot(model_3x3)
```
